### ISSUE TITLE
hc_tooltip(sort = TRUE, table = TRUE)

### ISSUE THREAD

**Issue by jbkunst** [d-qn/2017_03_01_swissWatch_TPT#1]
Hi @d-qn 

I'm very very glad you're using highcharter, it makes me very happy. Thanks. 

Have you tried use this shortcuts in `hc_tooltip`? In this project you have many series, maybe it's usefull to comapare simultaneously all countries in a year.

sort: to sort the series according the y-value,
table: to put them in a table to align them.

```r
data <- map(1:10, function(x){
  list(data = cumsum(runif(20)))
})

highchart() %>% 
  hc_add_series_list(data) %>% 
  hc_chart(type = "areaspline") %>% 
  hc_plotOptions(series = list(stacking = "normal")) %>% 
  hc_tooltip(sort = TRUE, table = TRUE, valueDecimals = 2)
```

![image](https://cloud.githubusercontent.com/assets/56481/23558287/c61f8acc-0011-11e7-9996-e989f890342c.png)

**Comment by d-qn** [comment]
Hi Joshua,

thanks for your message and for checking on my highcharter usage :-) I am very very glad highcharter exists, I don't know what I would do without it! Thank you for this great package. 

About the tooltip with series, great suggestion, cheers! I will try it out for my next charts to publish. I agree such tooltip is much nicer on desktop. However, I am just afraid that it would be mobile-unfriendly by being so big. And mobile first is a big thing for my employer. I will try it though. Thanks for the suggestion!

**Comment by jbkunst** [comment]
I understand, no problem. You're right.

Remember, if you need anything that could enhancement the package open a issue. I would like to help you.

**Comment by d-qn** [comment]
Thanks a lot for the offer! Ok, I will definitely bother you with feature requests :-)
